### ISSUE TITLE
How to create Multi-tenancy with EF Core in Blazor Webassembly 

### ISSUE THREAD

**Issue by jasielbr** [JeremyLikness/jeremylikness-blog#15]
hi i saw your content in this post, but how could i do it for wasm blazor?

https://blog.jeremylikness.com/blog/multitenancy-with-ef-core-in-blazor-server-apps/

**Comment by JeremyLikness** [comment]
Wasm is even easier because you would stand up EF Core in an API and the API would resolve the tenant when fetching the context.
