### ISSUE TITLE
CLI commands to create App in AAD

### ISSUE THREAD

**Issue by enijburg** [JeremyLikness/jeremylikness-blog#3]
Hi Jeremy,

Thanks for the good write-up, saved me quite some research. I have created a small CLI script to ease up the Azure Active Directory manual labor.

`$appName = "BlazorTest1"
$replyUrl = "https://localhost:44324/authentication/login-callback"

az login

$graphId = az ad sp list --query "[?appDisplayName=='Microsoft Graph'].appId | [0]" --all 

$userRead = az ad sp show --id $graphId --query "oauth2Permissions[?value=='User.Read'].id | [0]"

$resources = @"
[{ "resourceAppId": $graphId, "resourceAccess": [{"id": $userRead,"type": "Scope"}]}]
"@ | ConvertTo-Json

az ad app create --display-name $appName --reply-urls $replyUrl --required-resource-accesses $resources --available-to-other-tenants false --oauth2-allow-implicit-flow true

$appId=$(az ad app list --display-name $appName --query [].appId -o tsv)
$tenantId = $(az account get-access-token --query tenant --output tsv)

Write-Output "ClientID: $($appId)"
Write-Output "TenantID: $($tenantId)"`

**Comment by JeremyLikness** [comment]
@enijburg thanks for this. I assume this scripts the Blazor Wasm side, not the Cosmos side? What would be awesome is if you put this in a https://gist.github.com then you can post the link in the comments on the blog post. Thoughts?

**Comment by enijburg** [comment]
@JeremyLikness, I will create the gists for both.
